# Generated by Django 4.0.5 on 2022-06-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
